#!/usr/bin/env bash
set -eu
SCRIPTS=`dirname $0`
BASEDIR=$SCRIPTS/..
ruby -I $BASEDIR/tests/integration/vendor/lib \
    -I $BASEDIR/tests/fixtures/plugins/ \
    -rpuppet \
    $BASEDIR/tests/integration/vendor/bin/mco $@ --config $BASEDIR/client.cfg
